### ISSUE TITLE
疑惑:为啥h5能加载出商品列表，运行到微信开发者工具就不行呢

### ISSUE THREAD

**Issue by isliwei** [dawang90/taro-duoduojinbao#1]
![image](https://user-images.githubusercontent.com/49444387/96332748-60cc3080-1098-11eb-8402-9c1f523d13e6.png)

**Comment by dawang90** [comment]
小程序需要添加请求白名单，或者开发者工具项目设置里去掉业务域名验证

**Comment by isliwei** [comment]
> 小程序需要添加请求白名单，或者开发者工具项目设置里去掉业务域名验证
已勾选不校验合法域名也是一样

**Comment by dawang90** [comment]
控制台的错误提示是什么

**Comment by isliwei** [comment]
没有报错才是最骚的，哈哈哈

**Comment by isliwei** [comment]
我自己研究下吧，谢谢你
